apiVersion: v1
kind: Namespace
metadata:
  name: streamlit-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-frontend
  namespace: streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-frontend
  template:
    metadata:
      labels:
        app: streamlit-frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: streamlit-frontend
                topologyKey: kubernetes.io/hostname
      containers:
        - name: streamlit-frontend
          image: 932566365205.dkr.ecr.ap-south-2.amazonaws.com/streamlit_repo:v1
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
